services:
  web:
    image: ghcr.io/edward0127/curtain_b2b_quote:latest
    security_opt:
      - seccomp=unconfined
    container_name: curtain_b2b_quote
    restart: unless-stopped
    ports:
      - "${APP_PORT_BIND:-3012}:80"
    env_file:
      - .env.prod
    volumes:
      - curtain_storage:/rails/storage
      - curtain_db:/data

volumes:
  curtain_storage:
  curtain_db: